-- Script SQL para inicializar la base de datos de WebDevLingo
-- Ejecuta este script en el SQL Editor de tu Dashboard de Supabase: https://supabase.com/dashboard

-- 1. Crear la tabla 'vocabulary' si no existe
CREATE TABLE IF NOT EXISTS public.vocabulary (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    term text not null,
    translation text not null,
    definition text not null,
    context text
);

-- 2. Habilitar Row Level Security (RLS)
ALTER TABLE public.vocabulary ENABLE ROW LEVEL SECURITY;

-- 3. Crear política para permitir acceso público de LECTURA (SELECT)
-- Esto permite que cualquiera (incluso usuarios no autenticados) pueda leer el vocabulario.
create policy "Acceso público de lectura al vocabulario"
on public.vocabulary for select
to anon
using (true);

-- 4. Insertar datos iniciales (Seed Data)
INSERT INTO public.vocabulary (term, translation, definition, context) 
VALUES
('API', 'Interfaz de Programación de Aplicaciones', 'Conjunto de reglas que permite que diferentes aplicaciones se comuniquen entre sí.', 'Cuando tu frontend pide datos a tu servidor, probablemente lo hace a través de una API REST.'),
('Backend', 'Desarrollo del lado del servidor', 'La parte de una aplicación web que no es visible para el usuario final. Gestiona la lógica, bases de datos y seguridad.', 'Node.js, Python (Django/Flask) y PHP son tecnologías comunes de Backend.'),
('Frontend', 'Desarrollo del lado del cliente', 'La parte de la web con la que el usuario interactúa directamente. Se encarga de la estructura, diseño y dinamismo visual.', 'HTML, CSS, JavaScript y frameworks como React o Vue viven aquí.'),
('DOM', 'Modelo de Objetos del Documento', 'Representación estructurada de un documento HTML que permite a un lenguaje de programación (como JS) manipular el contenido y estilo.', 'JavaScript usa "document.getElementById" para encontrar elementos en el DOM.'),
('Framework', 'Marco de trabajo', 'Estructura base que sirve como punto de partida para desarrollar software, ofreciendo herramientas y buenas prácticas predefinidas.', 'React, Angular y Vue son frameworks (o librerías con ecosistema) de JS; Bootstrap es un framework de CSS.'),
('Deploy', 'Despliegue', 'El proceso de poner una aplicación web o sitio disponible en un servidor para que sea accesible públicamente en internet.', 'Acabo de hacer deploy de mi app en Vercel.'),
('Bug', 'Error de software', 'Fallo o defecto en un programa de ordenador que impide que este funcione correctamente.', 'Tengo un bug en el formulario de contacto que no permite enviarlo.'),
('Responsive Design', 'Diseño Responsivo', 'Técnica de diseño web que busca que la apariencia y comportamiento de un sitio se adapte al tamaño de pantalla del dispositivo.', 'Gracias a las Media Queries, este sitio tiene un diseño responsivo.'),
('Full Stack', 'Desarrollador completo', 'Perfil profesional que tiene conocimientos tanto de Frontend como de Backend.', 'Un desarrollador Full Stack puede crear una web completa desde la base de datos hasta la interfaz de usuario.'),
('Git', 'Sistema de control de versiones', 'Herramienta que permite rastrear cambios en el código fuente durante el desarrollo de software.', 'Recuerda hacer commit y push de tus cambios en Git.');

-- 5. Crear la tabla de historial de búsqueda
CREATE TABLE IF NOT EXISTS public.history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    word text not null
);

-- 6. Habilitar RLS para el historial
ALTER TABLE public.history ENABLE ROW LEVEL SECURITY;

-- 7. Políticas para el historial (Solo el usuario puede ver/crear sus datos)
CREATE POLICY "Usuarios pueden ver su propio historial"
ON public.history FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Usuarios pueden insertar su propio historial"
ON public.history FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Confirmación final
select count(*) as term_count from public.vocabulary;
select count(*) as history_count from public.history;
